### ISSUE TITLE
Database: Handle database index 

### ISSUE THREAD

**Issue by Netanel-Iyov** [amir3x0/Cloud-Project-Nvidia#8]
Agreed that index fields will look like that: 

[
	{
		Term: 'GPU',
		DocsIDs: [ 
			{ 'url': 'link1', 'headline': 'example_headline, 'description': 'example_description'}, 
			{} 
		]
	},
	{
		Term: 'GTX1050',
		DocsIDs: [ 
			{ 'url': 'link1', 'headline': 'example_headline, 'description': 'example_description'}, 
			{} 
		]
	}
]

**Comment by rsCode1** [comment]
done
